![](../docs/banner.png)

# NumPy


## Exercises

### 1.

Import numpy under the alias `np`.

In [4]:

import numpy as np


### 2.

Create the following arrays:

1. Create an array of 5 zeros.
2. Create an array of 10 ones.
3. Create an array of 5 3.141s.
4. Create an array of the integers 1 to 20.
5. Create a 5 x 5 matrix of ones with a dtype `int`.

In [10]:

zeros_array = np.zeros(5)
ones_array = np.ones(10)
pi_array = np.full(5, 3.141)
integers_array = np.arange(1,21)
ones_matrix = np.ones((5, 5), dtype=int)


### 3.

Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [9]:

random_val=np.random.randn(3,3,3)
random_reshape=random_val.reshape(27)

### 4.

Create an array of 20 linearly spaced numbers between 1 and 10.

In [8]:
linearly_spaced=np.linspace(1,10,20)
print(linearly_spaced)


[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### 5.

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [12]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)

```python
20
```

In [13]:
output1 = a[3,4]
print(output1)

20


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [14]:

output2 = a[1:6, 3:5]
print(output2)

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([ 6,  7,  8,  9, 10])
```

In [15]:
output3 = a[1, :]
print(output3)

[ 6  7  8  9 10]


```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [ ]:
output4 = a[2:4, :]
print(output4)

```python
array([[ 8,  9],
       [13, 14]])
```

In [16]:
output5 = a[1:3, 2:4]
print(output5)

[[ 8  9]
 [13 14]]


### 6.

Calculate the sum of all the numbers in `a`.

In [20]:
a = np.arange(1, 26).reshape(5, 5)

sum_of_all_numbers = np.sum(a)

print(sum_of_all_numbers)


325


### 7.

Calculate the sum of each row in `a`.

In [21]:
sum_of_each_row = np.sum(a, axis=1)
print(sum_of_each_row)

[ 15  40  65  90 115]


### 8.

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [22]:
mean_of_a = np.mean(a)

mask = a > mean_of_a

values_greater_than_mean = a[mask]

print(a)

print("\nMean of the array:", mean_of_a)

print("\nValues greater than the mean:")
print(values_greater_than_mean)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Mean of the array: 13.0

Values greater than the mean:
[14 15 16 17 18 19 20 21 22 23 24 25]


### 9.

Find the location of the minimum value in the following array `b`:

In [23]:
np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [24]:
b
min_index = np.argmin(b)
print(min_index)

6


### 10.

Find the location of the maximum value in the following 2D array `c` (hint: there are many ways to do this question, but a quick search on stackoverflow.com will typically help you find the optimum solution for a problem, for example see [post](https://stackoverflow.com/questions/3584243/get-the-position-of-the-biggest-item-in-a-multi-dimensional-numpy-array)):

In [26]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [27]:
max_index = np.unravel_index(np.argmax(c), c.shape)
print(max_index)

(2, 1)


<hr>
<hr>
<hr>